### ISSUE TITLE
underline in YAML files

### ISSUE THREAD

**Issue by nobler1050** [jnurmine/Zenburn#18]
Is it supposed to underline in YAML files?  In the sample below the "- ", the dash and the space, before name would be underlined when using zenburn in vim.  

# tasks file for Ansible role                                                                                                                    
- name: description of task                                                                                                              
  template: src=file.conf.j2 dest=file.conf                                                                       
  notify: restart handler

**Comment by jnurmine** [comment]
No, it's not - it seems to map to `lo<Label>` which is indeed underlined and does not look so nice.

It's a bit tricky to fix properly since Vim loads the color file at startup and then the colors just linger around. The color scheme is not checked at every file open.

If you work predominantly on YAML files, you might want to use `let g:zenburn_disable_Label_underline=1` to avoid the underline.

Alternatively, to target YAML files only, do this in your .vimrc:

`autocmd FileType yaml highlight! def link yamlBlockCollectionItemStart NONE`
