### ISSUE TITLE
Cursor is too Dark

### ISSUE THREAD

**Issue by thecapacity** [jnurmine/Zenburn#19]
<img width="147" alt="screen shot 2016-10-20 at 12 59 56 pm" src="https://cloud.githubusercontent.com/assets/57710/19569832/2af5c9f4-96c5-11e6-8f94-88d9bdd87aeb.png">

I've tried tons of googling and random vim commands but I can't seem to set the cursor color to _anything_ let alone something that's visible. 

I love zenburn but it's currently unusable for me because I can't find my cursor at all (which is usually somewhat problematic but this is beyond...)

Please help! I think something darker would help but I tried the `let g:zenburn_old_Visual = 1` and got no results.

This is using straight vim in a Mac Term window.
thanks!

**Comment by thecapacity** [comment]
Note the cursor is on the line just above `print(...)` in the attached screenshot

**Comment by jnurmine** [comment]
Hi, this is due to the terminal application. I don't have a Mac Term at hand, but I'd guess your best bet is to use escape sequences accepted by your terminal in your .vimrc. Or, configure the terminal via its GUI if there's such a setting.

Also, test first in the terminal with:
`printf '\033]50;CursorShape=2\x7`
and
`printf '\033]50;CursorShape=0\x7`

If those changed the cursor, please try something like this in .vimrc:

```
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
let &t_SI = "\<Esc>]50;CursorShape=0\x7"
```

If there was no change, the escape sequences above do not work.

**Comment by thecapacity** [comment]
Thanks, it doesn't look like that changed the cursor... I'm not sure why it's MacTerm specific though?

i.e. can't I just make the cursor yellow or something via a .vimrc file?

Really appreciate the feedback!

**Comment by jnurmine** [comment]
Yes, extra ' was a good addition, I misplaced it, sorry.

Vim uses the terminal escape sequences to change things like the cursor color. If some particular code is not supported by the terminal, nothing happens.

I had a look at some Mac Term screenshots. Are you using Mac Term in Terminals/Emulation/Base Emulator "XTerm" (and xterm-256color) mode? Maybe there is some "Emulation Tweak" which can be enabled?
