### ISSUE TITLE
Terminal Ansi Colors twisted?

### ISSUE THREAD

**Issue by 8FordPrefect8** [jnurmine/Zenburn#31]
Hi,
sorry if it's a stupid question and maybe it's intended.

I tried to set up my kitty theme along the zenburn colors I use in vim. Unfortunately the config I found searching the web differs actually in colors.
So now I looked up the original code to find the actual colors and entered them as listed here:
' let g:terminal_ansi_colors = [
        \ '#1f1f1f', '#cc9393',
        \ '#5f7f5f', '#ffd7a7',
        \ '#8cb0d3', '#8f8f8f',
        \ '#71d3b4', '#dfe4cf',
        \ '#6f6f6f', '#ecb3b3',
        \ '#ffd7a7', '#8cb0d3',
        \ '#8f8f8f', '#71d3b4',
        \ '#dfe4cf', '#ffcfaf',
        \]'
First thing I noticed is that for most colors there is no difference in bright and normal, but I guess it's intended. Second thing I noticed is that they don't line up. They are all skipped by one. So nr. 7 is white as expected and 15 should be typically a bright white, but it's a yellow/orange color. The second white is at color 14 instead.

To implement that I am wondering now whether something got mixed up here unintended or whether it is on purpose to give a better impression. I have no clue about proper color design so I really don't no.

**Comment by jnurmine** [comment]
Hi,

it's not a stupid question and I don't have a clue about proper color design either :)

The `terminal_ansi_colors` is a new thing for Vim 8.2+, meant for the Vim `:terminal` command to make it look more Zenburn-like. It's not really meant for a general purpose terminal theme.

To my understanding, terminal colors are just made to look nice. Maybe there's some underlying big idea in some standards base, like "directories shall be blue", but I don't know of it.

Also, the light/dark separation does not carry information that I know of. For example, directory names could be light blue but then dark blue might turn up for some type of file like .mp4. In Linux there's a command called `dircolors` which defines this color setup used by the `ls` command and it can be changed by the user as they see fit. Try `dircolors --print-database` to see some details.

The double `#dfe4cf` in the `terminal_ansi_colors` is probably because the color 14 was not visible anywhere in the `:terminal`, so I left a default/copy-paste value to that color. It should probably be changed but hard to say how.

I'd suggest to reuse the Kitty theme you found and/or the Vim `terminal_ansi_colors` and if you like the overall palette (right colours, wrong order)... maybe just swap colors around until the result looks nice.

**Comment by 8FordPrefect8** [comment]
Thanks for your Feedback. You are right I could just take similar colors that are nice. It's more a sway ricing thing that I want to work with one set of colors matching up and setting them in all config files.

**Comment by jnurmine** [comment]
Hi,

not sure if I can do anything more for this... I'll close the ticket

Cheers!
